<!DOCTYPE html>
<html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>Propuesta de Análisis | Análisis de Series de Tiempo de Precios de Acciones</title>
<meta name="author" content="Julian Rojas y Natalia Tangarife">
<meta name="description" content="Análisis de series de tiempo de precios de acciones durante el período COVID-19 y su integración con modelos de valoración de opciones financieras.">
<meta name="generator" content="bookdown 0.45 with bs4_book()">
<meta property="og:title" content="Propuesta de Análisis | Análisis de Series de Tiempo de Precios de Acciones">
<meta property="og:type" content="book">
<meta property="og:description" content="Análisis de series de tiempo de precios de acciones durante el período COVID-19 y su integración con modelos de valoración de opciones financieras.">
<meta name="twitter:card" content="summary">
<meta name="twitter:title" content="Propuesta de Análisis | Análisis de Series de Tiempo de Precios de Acciones">
<meta name="twitter:description" content="Análisis de series de tiempo de precios de acciones durante el período COVID-19 y su integración con modelos de valoración de opciones financieras.">
<!-- JS --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/fuse.js/6.4.6/fuse.js" integrity="sha512-zv6Ywkjyktsohkbp9bb45V6tEMoWhzFzXis+LrMehmJZZSys19Yxf1dopHx7WzIKxr5tK2dVcYmaCk2uqdjF4A==" crossorigin="anonymous"></script><script src="https://kit.fontawesome.com/6ecbd6c532.js" crossorigin="anonymous"></script><script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link href="libs/bootstrap-4.6.0/bootstrap.min.css" rel="stylesheet">
<script src="libs/bootstrap-4.6.0/bootstrap.bundle.min.js"></script><script src="libs/bs3compat-0.9.0/transition.js"></script><script src="libs/bs3compat-0.9.0/tabs.js"></script><script src="libs/bs3compat-0.9.0/bs3compat.js"></script><link href="libs/bs4_book-1.0.0/bs4_book.css" rel="stylesheet">
<script src="libs/bs4_book-1.0.0/bs4_book.js"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/autocomplete.js/0.38.0/autocomplete.jquery.min.js" integrity="sha512-GU9ayf+66Xx2TmpxqJpliWbT5PiGYxpaG8rfnBEk1LL8l1KGkRShhngwdXK1UgqhAzWpZHSiYPc09/NwDQIGyg==" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mark.js/8.11.1/mark.min.js" integrity="sha512-5CYOlHXGh6QpOFA/TeTylKLWfB3ftPsde7AnmhuitiTX4K5SqCLBeKro6sPS8ilsz1Q4NRx3v8Ko2IBiszzdww==" crossorigin="anonymous"></script><!-- CSS --><style type="text/css">
    
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  </style>
</head>
<body data-spy="scroll" data-target="#toc">

<div class="container-fluid">
<div class="row">
  <header class="col-sm-12 col-lg-3 sidebar sidebar-book"><a class="sr-only sr-only-focusable" href="#content">Skip to main content</a>

    <div class="d-flex align-items-start justify-content-between">
      <h1>
        <a href="index.html" title="">Análisis de Series de Tiempo de Precios de Acciones</a>
      </h1>
      <button class="btn btn-outline-primary d-lg-none ml-2 mt-1" type="button" data-toggle="collapse" data-target="#main-nav" aria-expanded="true" aria-controls="main-nav"><i class="fas fa-bars"></i><span class="sr-only">Show table of contents</span></button>
    </div>

    <div id="main-nav" class="collapse-lg">
      <form role="search">
        <input id="search" class="form-control" type="search" placeholder="Search" aria-label="Search">
</form>

      <nav aria-label="Table of contents"><h2>Table of contents</h2>
        <ul class="book-toc list-unstyled">
<li><a class="active" href="index.html">Propuesta de Análisis</a></li>
<li><a class="" href="literature.html"><span class="header-section-number">1</span> Literature</a></li>
<li><a class="" href="methods.html"><span class="header-section-number">2</span> Methods</a></li>
<li><a class="" href="applications.html"><span class="header-section-number">3</span> Applications</a></li>
<li><a class="" href="final-words.html"><span class="header-section-number">4</span> Final Words</a></li>
<li><a class="" href="references.html">References</a></li>
</ul>

        <div class="book-extra">
          
        </div>
      </nav>
</div>
  </header><main class="col-sm-12 col-md-9 col-lg-7" id="content"><!--bookdown:title:end--><!--bookdown:title:start--><div id="propuesta-de-análisis" class="section level1 unnumbered">
<h1>Propuesta de Análisis<a class="anchor" aria-label="anchor" href="#propuesta-de-an%C3%A1lisis"><i class="fas fa-link"></i></a>
</h1>
<div id="información-a-utilizar" class="section level2" number="0.1">
<h2>
<span class="header-section-number">0.1</span> Información a Utilizar<a class="anchor" aria-label="anchor" href="#informaci%C3%B3n-a-utilizar"><i class="fas fa-link"></i></a>
</h2>
<p>Para este curso trabajaremos con <strong>series de tiempo de precios diarios de acciones</strong> de seis empresas cotizadas en mercados estadounidenses, divididas en dos sectores:</p>
<ul>
<li>
<strong>Tecnología:</strong> Apple (AAPL), Microsoft (MSFT), Tesla (TSLA)</li>
<li>
<strong>Farmacéuticas:</strong> Pfizer (PFE), Moderna (MRNA), Johnson &amp; Johnson (JNJ)</li>
</ul>
<p>Los datos abarcan el período <strong>2015-2025 (10 años)</strong>, proporcionando un total de <strong>14,286 observaciones</strong>. Las variables incluyen precios de cierre, apertura, máximos, mínimos y volúmenes de negociación diarios, obtenidos mediante la librería <code>quantmod</code> que accede a <strong>Yahoo Finance</strong>.</p>
<div id="estadísticas-descriptivas-del-dataset" class="section level3" number="0.1.1">
<h3>
<span class="header-section-number">0.1.1</span> Estadísticas Descriptivas del Dataset<a class="anchor" aria-label="anchor" href="#estad%C3%ADsticas-descriptivas-del-dataset"><i class="fas fa-link"></i></a>
</h3>
<div class="inline-table"><table class="table table-sm">
<caption>
<span id="tab:tabla-resumen">Table 0.1: </span>Estadísticas descriptivas de las series de tiempo analizadas
</caption>
<thead><tr>
<th style="text-align:left;">
Ticker
</th>
<th style="text-align:left;">
Sector
</th>
<th style="text-align:right;">
Obs.
</th>
<th style="text-align:center;">
Inicio
</th>
<th style="text-align:center;">
Fin
</th>
<th style="text-align:right;">
Precio.Mín….
</th>
<th style="text-align:right;">
Precio.Máx….
</th>
<th style="text-align:right;">
Volatilidad….
</th>
<th style="text-align:right;">
Retorno.Total….
</th>
</tr></thead>
<tbody>
<tr>
<td style="text-align:left;">
AAPL
</td>
<td style="text-align:left;">
Tecnología
</td>
<td style="text-align:right;">
2514
</td>
<td style="text-align:center;">
2015-10-13
</td>
<td style="text-align:center;">
2025-10-10
</td>
<td style="text-align:right;">
22.58
</td>
<td style="text-align:right;">
259.02
</td>
<td style="text-align:right;">
29.21
</td>
<td style="text-align:right;">
777.61
</td>
</tr>
<tr>
<td style="text-align:left;">
MSFT
</td>
<td style="text-align:left;">
Tecnología
</td>
<td style="text-align:right;">
2514
</td>
<td style="text-align:center;">
2015-10-13
</td>
<td style="text-align:center;">
2025-10-10
</td>
<td style="text-align:right;">
46.68
</td>
<td style="text-align:right;">
535.64
</td>
<td style="text-align:right;">
26.96
</td>
<td style="text-align:right;">
989.70
</td>
</tr>
<tr>
<td style="text-align:left;">
TSLA
</td>
<td style="text-align:left;">
Tecnología
</td>
<td style="text-align:right;">
2514
</td>
<td style="text-align:center;">
2015-10-13
</td>
<td style="text-align:center;">
2025-10-10
</td>
<td style="text-align:right;">
9.58
</td>
<td style="text-align:right;">
479.86
</td>
<td style="text-align:right;">
59.30
</td>
<td style="text-align:right;">
2728.89
</td>
</tr>
<tr>
<td style="text-align:left;">
PFE
</td>
<td style="text-align:left;">
Farmacéutica
</td>
<td style="text-align:right;">
2514
</td>
<td style="text-align:center;">
2015-10-13
</td>
<td style="text-align:center;">
2025-10-10
</td>
<td style="text-align:right;">
21.59
</td>
<td style="text-align:right;">
61.25
</td>
<td style="text-align:right;">
24.00
</td>
<td style="text-align:right;">
-20.81
</td>
</tr>
<tr>
<td style="text-align:left;">
MRNA
</td>
<td style="text-align:left;">
Farmacéutica
</td>
<td style="text-align:right;">
1720
</td>
<td style="text-align:center;">
2018-12-07
</td>
<td style="text-align:center;">
2025-10-10
</td>
<td style="text-align:right;">
12.26
</td>
<td style="text-align:right;">
484.47
</td>
<td style="text-align:right;">
72.08
</td>
<td style="text-align:right;">
44.25
</td>
</tr>
<tr>
<td style="text-align:left;">
JNJ
</td>
<td style="text-align:left;">
Farmacéutica
</td>
<td style="text-align:right;">
2514
</td>
<td style="text-align:center;">
2015-10-13
</td>
<td style="text-align:center;">
2025-10-10
</td>
<td style="text-align:right;">
94.53
</td>
<td style="text-align:right;">
191.08
</td>
<td style="text-align:right;">
18.40
</td>
<td style="text-align:right;">
99.81
</td>
</tr>
</tbody>
</table></div>
<p><strong>Tabla 1.</strong> Resumen estadístico del dataset con 6 activos y 14,286 observaciones totales. Tesla presenta el mayor retorno (+2,728%) y Moderna la mayor volatilidad (72%).</p>
<p>Este período incluye cuatro fases claramente diferenciadas:</p>
<ul>
<li>
<strong>Pre-COVID (2015-2019):</strong> Período de crecimiento estable y expansión económica</li>
<li>
<strong>Crisis COVID-19 (2020):</strong> Caída abrupta del mercado y alta volatilidad</li>
<li>
<strong>Período de Vacunas (2021):</strong> Desarrollo y distribución de vacunas COVID-19</li>
<li>
<strong>Post-pandemia (2022-2025):</strong> Nuevas dinámicas de mercado</li>
</ul>
</div>
<div id="comparación-por-sector" class="section level3" number="0.1.2">
<h3>
<span class="header-section-number">0.1.2</span> Comparación por Sector<a class="anchor" aria-label="anchor" href="#comparaci%C3%B3n-por-sector"><i class="fas fa-link"></i></a>
</h3>
<div class="figure">
<span style="display:block;" id="fig:figura-sectores"></span>
<img src="graficos/03_comparacion_sector.png" alt="Comparación de desempeño normalizado por sector. Panel superior: Farmacéuticas con Moderna mostrando crecimiento explosivo durante vacunas. Panel inferior: Tecnología con Tesla liderando los retornos. Líneas rojas verticales marcan el período COVID-19." width="100%"><p class="caption">
Figure 0.1: Comparación de desempeño normalizado por sector. Panel superior: Farmacéuticas con Moderna mostrando crecimiento explosivo durante vacunas. Panel inferior: Tecnología con Tesla liderando los retornos. Líneas rojas verticales marcan el período COVID-19.
</p>
</div>
<p>La Figura 1 muestra el comportamiento diferenciado entre sectores. El sector tecnológico presenta crecimiento sostenido con Tesla liderando (+2,728%), mientras que el farmacéutico muestra un pico en Moderna durante vacunas seguido de corrección. Este contraste será analizado en capítulos posteriores.</p>
</div>
</div>
<div id="importancia-del-pronóstico-y-valor-agregado" class="section level2" number="0.2">
<h2>
<span class="header-section-number">0.2</span> Importancia del Pronóstico y Valor Agregado<a class="anchor" aria-label="anchor" href="#importancia-del-pron%C3%B3stico-y-valor-agregado"><i class="fas fa-link"></i></a>
</h2>
<div id="el-problema" class="section level3" number="0.2.1">
<h3>
<span class="header-section-number">0.2.1</span> El Problema<a class="anchor" aria-label="anchor" href="#el-problema"><i class="fas fa-link"></i></a>
</h3>
<p>Los mercados financieros presentan comportamientos complejos que se intensifican durante crisis globales. El COVID-19 evidenció esto cuando los mercados experimentaron caídas abruptas, alta volatilidad y recuperaciones diferenciadas por sector. Los inversionistas y gestores de riesgo necesitan herramientas para anticipar movimientos de precios incluso en contextos de alta incertidumbre.</p>
</div>
<div id="el-valor-agregado" class="section level3" number="0.2.2">
<h3>
<span class="header-section-number">0.2.2</span> El Valor Agregado<a class="anchor" aria-label="anchor" href="#el-valor-agregado"><i class="fas fa-link"></i></a>
</h3>
<p>Este proyecto analiza <strong>series de tiempo de precios de acciones</strong> durante un período de 10 años que incluye eventos extremos. El valor agregado reside en:</p>
<p><strong>1. Análisis con Datos Reales Abundantes:</strong> Con 14,286 observaciones totales (2,514 por activo principal y 1,720 para MRNA), los análisis tienen suficiente poder estadístico para identificar patrones robustos, tendencias de largo plazo y quiebres estructurales.</p>
<p><strong>2. Múltiples Regímenes de Mercado:</strong> El período analizado captura diferentes contextos de mercado, desde estabilidad pre-COVID hasta volatilidad extrema durante la pandemia (hasta 72% anual en MRNA) y posterior normalización.</p>
<p><strong>3. Eventos Extremos Documentados:</strong> El dataset incluye el crash de marzo 2020, el desarrollo de vacunas y la recuperación post-pandemia, permitiendo estudiar quiebres estructurales en series de tiempo y evaluar capacidad predictiva ante eventos de baja probabilidad pero alto impacto.</p>
<p><strong>4. Comparación Intersectorial Cuantificada:</strong> Los datos revelan contrastes marcados:</p>
<ul>
<li>
<strong>Tecnología:</strong> Retornos totales entre +777% (AAPL) y +2,728% (TSLA)</li>
<li>
<strong>Farmacéuticas:</strong> Comportamiento heterogéneo desde -20% (PFE) hasta +44% (MRNA)</li>
<li>
<strong>Volatilidad:</strong> Rango de 18% (JNJ) hasta 72% (MRNA)</li>
</ul>
<p><strong>5. Caracterización Estadística:</strong> Los datos permiten identificar propiedades como estacionariedad, autocorrelación, heterocedasticidad y cambios de régimen en volatilidad, aspectos que serán desarrollados en capítulos posteriores.</p>
<p><strong>6. Aplicación a Valoración de Opciones:</strong> Los análisis de volatilidad histórica y comportamiento de precios se integran con el modelo Black-Scholes para mejorar la valoración de opciones financieras.</p>
</div>
</div>
<div id="fuentes-de-datos-y-permisos-de-uso" class="section level2" number="0.3">
<h2>
<span class="header-section-number">0.3</span> Fuentes de Datos y Permisos de Uso<a class="anchor" aria-label="anchor" href="#fuentes-de-datos-y-permisos-de-uso"><i class="fas fa-link"></i></a>
</h2>
<p><strong>Fuente:</strong> Yahoo Finance a través de la librería <code>quantmod</code> en R. Es una fuente pública reconocida en el sector financiero que permite acceso a datos históricos sin restricciones para uso académico y de investigación.</p>
<p><strong>Especificaciones técnicas:</strong></p>
<ul>
<li>
<strong>Período:</strong> 2015-2025 (10 años, excepto MRNA que inicia en 2018)</li>
<li>
<strong>Observaciones totales:</strong> 14,286 datos distribuidos en 6 activos</li>
<li>
<strong>Frecuencia:</strong> Diaria (aproximadamente 252 días de trading por año)</li>
<li>
<strong>Acceso:</strong> API pública sin permisos especiales requeridos</li>
<li>
<strong>Rango de precios:</strong> Desde $9.58 (TSLA mínimo) hasta $535.64 (MSFT máximo)</li>
</ul>
<p><strong>Variables recopiladas:</strong></p>
<ul>
<li>Precios: Cierre, apertura, máximo, mínimo (valores diarios en USD)</li>
<li>Volumen de negociación diario</li>
<li>Variables derivadas: Retornos diarios, retornos logarítmicos, volatilidad histórica</li>
<li>Clasificación temporal: Períodos COVID (Pre, Pandemia, Vacunas, Post)</li>
</ul>
</div>
<div id="impacto-esperado" class="section level2" number="0.4">
<h2>
<span class="header-section-number">0.4</span> Impacto Esperado<a class="anchor" aria-label="anchor" href="#impacto-esperado"><i class="fas fa-link"></i></a>
</h2>
<p>El análisis de series de tiempo con más de 14,000 observaciones reales beneficia a:</p>
<p><strong>Inversionistas:</strong> Comprensión documentada de cómo diferentes sectores responden a choques sistémicos, con evidencia cuantitativa de retornos y volatilidades observados durante crisis.</p>
<p><strong>Gestores de riesgo:</strong> Identificación de patrones de volatilidad durante eventos extremos, con datos reales que muestran variaciones desde 18% hasta 72% de volatilidad anualizada según el activo y el período.</p>
<p><strong>Analistas financieros:</strong> Caracterización cuantitativa de resiliencia sectorial respaldada por datos históricos de una década, incluyendo el evento más disruptivo de los mercados financieros en la última generación.</p>
<p><strong>Traders de opciones:</strong> Estimación mejorada de volatilidad para valoración de derivados, con datos históricos que documentan cambios de régimen en volatilidad durante diferentes fases del mercado.</p>
<p><strong>Académicos:</strong> Evidencia empírica robusta sobre comportamiento de series financieras durante crisis globales, con suficientes observaciones para análisis estadísticamente significativos y validación de modelos de series de tiempo.</p>
<hr>
<p><strong>Nota:</strong> Este documento constituye la propuesta inicial del proyecto. Los capítulos posteriores desarrollarán en detalle el análisis exploratorio de las series, pruebas de estacionariedad, modelado de volatilidad, identificación de quiebres estructurales y su integración con modelos de valoración de opciones financieras.</p>

</div>
<div id="intro" class="section level2" number="0.5">
<h2>
<span class="header-section-number">0.5</span> Visualización de las Series de Tiempo<a class="anchor" aria-label="anchor" href="#intro"><i class="fas fa-link"></i></a>
</h2>
<p>Las visualizaciones tienen como objetivo explorar y comunicar los patrones, tendencias y comportamientos presentes en las series de tiempo de precios de acciones durante el período 2015-2025, con énfasis en el impacto del COVID-19.</p>
</div>
<div id="series-de-tiempo-completas" class="section level2" number="0.6">
<h2>
<span class="header-section-number">0.6</span> Series de Tiempo Completas<a class="anchor" aria-label="anchor" href="#series-de-tiempo-completas"><i class="fas fa-link"></i></a>
</h2>
<p>Los siguientes gráficos proporcionan una visión general de la evolución de los precios de cada activo a lo largo del período 2015-2025.</p>
<div id="sector-tecnológico" class="section level3" number="0.6.1">
<h3>
<span class="header-section-number">0.6.1</span> Sector Tecnológico<a class="anchor" aria-label="anchor" href="#sector-tecnol%C3%B3gico"><i class="fas fa-link"></i></a>
</h3>
<div class="figure">
<span style="display:block;" id="fig:series-tech"></span>
<img src="01-intro_files/figure-html/series-tech-1.png" alt="Series de tiempo del sector tecnológico. Se observa el crecimiento explosivo de Tesla post-2019, la estabilidad relativa de Apple y Microsoft, y el impacto del COVID-19 (área sombreada) en las tres empresas." width="672"><p class="caption">
Figure 0.2: Series de tiempo del sector tecnológico. Se observa el crecimiento explosivo de Tesla post-2019, la estabilidad relativa de Apple y Microsoft, y el impacto del COVID-19 (área sombreada) en las tres empresas.
</p>
</div>
<p><strong>Observaciones clave del sector tecnológico:</strong></p>
<ul>
<li><p><strong>Apple (AAPL):</strong> Muestra un crecimiento sostenido de $22.58 a $259.02 (+778%), con volatilidad moderada (29.2% anual). Durante el COVID-19, experimentó una caída breve seguida de recuperación acelerada.</p></li>
<li><p><strong>Microsoft (MSFT):</strong> Presenta el comportamiento más estable del sector con crecimiento constante de $46.68 a $535.64 (+990%). La volatilidad de 27% anual es la más baja del sector tecnológico. Mínima afectación durante el crash de marzo 2020.</p></li>
<li><p><strong>Tesla (TSLA):</strong> Exhibe el comportamiento más volátil (59.3% anual) y el mayor retorno (+2,729%). Se observa crecimiento casi exponencial desde 2019, con alta sensibilidad a eventos de mercado.</p></li>
</ul>
</div>
<div id="sector-farmacéutico" class="section level3" number="0.6.2">
<h3>
<span class="header-section-number">0.6.2</span> Sector Farmacéutico<a class="anchor" aria-label="anchor" href="#sector-farmac%C3%A9utico"><i class="fas fa-link"></i></a>
</h3>
<div class="figure">
<span style="display:block;" id="fig:series-pharma"></span>
<img src="01-intro_files/figure-html/series-pharma-1.png" alt="Series de tiempo del sector farmacéutico. Destaca el pico dramático de Moderna durante el período de vacunas (2020-2021), mientras que Pfizer y J&amp;J muestran comportamientos más estables." width="672"><p class="caption">
Figure 0.3: Series de tiempo del sector farmacéutico. Destaca el pico dramático de Moderna durante el período de vacunas (2020-2021), mientras que Pfizer y J&amp;J muestran comportamientos más estables.
</p>
</div>
<p><strong>Observaciones clave del sector farmacéutico:</strong></p>
<ul>
<li><p><strong>Pfizer (PFE):</strong> Comportamiento estable con retorno negativo (-20.8%). Volatilidad moderada (24% anual). Pico durante el anuncio y distribución de vacunas, seguido de corrección.</p></li>
<li><p><strong>Moderna (MRNA):</strong> La mayor volatilidad del dataset (72.1% anual). Crecimiento explosivo durante el desarrollo de vacunas (diciembre 2020), alcanzando $484.47 desde $12.26. Posterior corrección drástica reflejando la normalización post-pandemia.</p></li>
<li><p><strong>Johnson &amp; Johnson (JNJ):</strong> La menor volatilidad de todo el dataset (18.4% anual). Comportamiento defensivo con retorno total de +99.8%. Mínima afectación durante COVID-19.</p></li>
</ul>
</div>
</div>
<div id="análisis-con-promedios-móviles" class="section level2" number="0.7">
<h2>
<span class="header-section-number">0.7</span> Análisis con Promedios Móviles<a class="anchor" aria-label="anchor" href="#an%C3%A1lisis-con-promedios-m%C3%B3viles"><i class="fas fa-link"></i></a>
</h2>
<p>Los promedios móviles permiten suavizar la volatilidad diaria y visualizar tendencias subyacentes. Se calculan promedios de 7, 30 y 90 días.</p>
<div id="promedios-móviles---tecnología" class="section level3" number="0.7.1">
<h3>
<span class="header-section-number">0.7.1</span> Promedios Móviles - Tecnología<a class="anchor" aria-label="anchor" href="#promedios-m%C3%B3viles---tecnolog%C3%ADa"><i class="fas fa-link"></i></a>
</h3>
<pre><code>## Warning: Removed 6 rows containing missing values or values outside the scale range
## (`geom_line()`).</code></pre>
<pre><code>## Warning: Removed 29 rows containing missing values or values outside the scale range
## (`geom_line()`).</code></pre>
<pre><code>## Warning: Removed 89 rows containing missing values or values outside the scale range
## (`geom_line()`).</code></pre>
<div class="figure">
<span style="display:block;" id="fig:sma-tech-1"></span>
<img src="01-intro_files/figure-html/sma-tech-1.png" alt="Series con promedios móviles del sector tecnológico. Las líneas suavizadas (SMA 7, 30, 90 días) revelan las tendencias subyacentes y confirman el crecimiento sostenido post-COVID." width="672"><p class="caption">
Figure 0.4: Series con promedios móviles del sector tecnológico. Las líneas suavizadas (SMA 7, 30, 90 días) revelan las tendencias subyacentes y confirman el crecimiento sostenido post-COVID.
</p>
</div>
<pre><code>## Warning: Removed 6 rows containing missing values or values outside the scale range
## (`geom_line()`).</code></pre>
<pre><code>## Warning: Removed 29 rows containing missing values or values outside the scale range
## (`geom_line()`).</code></pre>
<pre><code>## Warning: Removed 89 rows containing missing values or values outside the scale range
## (`geom_line()`).</code></pre>
<div class="figure">
<span style="display:block;" id="fig:sma-tech-2"></span>
<img src="01-intro_files/figure-html/sma-tech-2.png" alt="Series con promedios móviles del sector tecnológico. Las líneas suavizadas (SMA 7, 30, 90 días) revelan las tendencias subyacentes y confirman el crecimiento sostenido post-COVID." width="672"><p class="caption">
Figure 0.5: Series con promedios móviles del sector tecnológico. Las líneas suavizadas (SMA 7, 30, 90 días) revelan las tendencias subyacentes y confirman el crecimiento sostenido post-COVID.
</p>
</div>
<pre><code>## Warning: Removed 6 rows containing missing values or values outside the scale range
## (`geom_line()`).</code></pre>
<pre><code>## Warning: Removed 29 rows containing missing values or values outside the scale range
## (`geom_line()`).</code></pre>
<pre><code>## Warning: Removed 89 rows containing missing values or values outside the scale range
## (`geom_line()`).</code></pre>
<div class="figure">
<span style="display:block;" id="fig:sma-tech-3"></span>
<img src="01-intro_files/figure-html/sma-tech-3.png" alt="Series con promedios móviles del sector tecnológico. Las líneas suavizadas (SMA 7, 30, 90 días) revelan las tendencias subyacentes y confirman el crecimiento sostenido post-COVID." width="672"><p class="caption">
Figure 0.6: Series con promedios móviles del sector tecnológico. Las líneas suavizadas (SMA 7, 30, 90 días) revelan las tendencias subyacentes y confirman el crecimiento sostenido post-COVID.
</p>
</div>
<p><strong>Interpretación de promedios móviles:</strong></p>
<ul>
<li>
<strong>SMA 7 días:</strong> Reacciona rápidamente a cambios, útil para identificar reversiones de corto plazo.</li>
<li>
<strong>SMA 30 días:</strong> Revela tendencias de mediano plazo, filtrando ruido diario.</li>
<li>
<strong>SMA 90 días:</strong> Muestra la tendencia de largo plazo, especialmente útil para identificar cambios de régimen durante COVID-19.</li>
</ul>
</div>
<div id="promedios-móviles---farmacéuticas" class="section level3" number="0.7.2">
<h3>
<span class="header-section-number">0.7.2</span> Promedios Móviles - Farmacéuticas<a class="anchor" aria-label="anchor" href="#promedios-m%C3%B3viles---farmac%C3%A9uticas"><i class="fas fa-link"></i></a>
</h3>
<pre><code>## Warning: Removed 6 rows containing missing values or values outside the scale range
## (`geom_line()`).</code></pre>
<pre><code>## Warning: Removed 29 rows containing missing values or values outside the scale range
## (`geom_line()`).</code></pre>
<pre><code>## Warning: Removed 89 rows containing missing values or values outside the scale range
## (`geom_line()`).</code></pre>
<div class="figure">
<span style="display:block;" id="fig:sma-pharma-1"></span>
<img src="01-intro_files/figure-html/sma-pharma-1.png" alt="Series con promedios móviles del sector farmacéutico. El caso de Moderna es particularmente interesante, mostrando cómo los promedios capturan el ciclo completo de auge y corrección." width="672"><p class="caption">
Figure 0.7: Series con promedios móviles del sector farmacéutico. El caso de Moderna es particularmente interesante, mostrando cómo los promedios capturan el ciclo completo de auge y corrección.
</p>
</div>
<pre><code>## Warning: Removed 6 rows containing missing values or values outside the scale range
## (`geom_line()`).</code></pre>
<pre><code>## Warning: Removed 29 rows containing missing values or values outside the scale range
## (`geom_line()`).</code></pre>
<pre><code>## Warning: Removed 89 rows containing missing values or values outside the scale range
## (`geom_line()`).</code></pre>
<div class="figure">
<span style="display:block;" id="fig:sma-pharma-2"></span>
<img src="01-intro_files/figure-html/sma-pharma-2.png" alt="Series con promedios móviles del sector farmacéutico. El caso de Moderna es particularmente interesante, mostrando cómo los promedios capturan el ciclo completo de auge y corrección." width="672"><p class="caption">
Figure 0.8: Series con promedios móviles del sector farmacéutico. El caso de Moderna es particularmente interesante, mostrando cómo los promedios capturan el ciclo completo de auge y corrección.
</p>
</div>
<pre><code>## Warning: Removed 6 rows containing missing values or values outside the scale range
## (`geom_line()`).</code></pre>
<pre><code>## Warning: Removed 29 rows containing missing values or values outside the scale range
## (`geom_line()`).</code></pre>
<pre><code>## Warning: Removed 89 rows containing missing values or values outside the scale range
## (`geom_line()`).</code></pre>
<div class="figure">
<span style="display:block;" id="fig:sma-pharma-3"></span>
<img src="01-intro_files/figure-html/sma-pharma-3.png" alt="Series con promedios móviles del sector farmacéutico. El caso de Moderna es particularmente interesante, mostrando cómo los promedios capturan el ciclo completo de auge y corrección." width="672"><p class="caption">
Figure 0.9: Series con promedios móviles del sector farmacéutico. El caso de Moderna es particularmente interesante, mostrando cómo los promedios capturan el ciclo completo de auge y corrección.
</p>
</div>
</div>
</div>
<div id="análisis-de-rezagos" class="section level2" number="0.8">
<h2>
<span class="header-section-number">0.8</span> Análisis de Rezagos<a class="anchor" aria-label="anchor" href="#an%C3%A1lisis-de-rezagos"><i class="fas fa-link"></i></a>
</h2>
<p>Los gráficos de rezago permiten identificar dependencia temporal en las series, evaluando si el precio de hoy está correlacionado con el precio de días anteriores.</p>
<pre><code>## Warning: Removed 1 row containing missing values or values outside the scale range
## (`geom_point()`).</code></pre>
<pre><code>## Warning: Removed 7 rows containing missing values or values outside the scale range
## (`geom_point()`).</code></pre>
<pre><code>## Warning: Removed 1 row containing missing values or values outside the scale range
## (`geom_point()`).</code></pre>
<pre><code>## Warning: Removed 7 rows containing missing values or values outside the scale range
## (`geom_point()`).</code></pre>
<pre><code>## Warning: Removed 1 row containing missing values or values outside the scale range
## (`geom_point()`).</code></pre>
<pre><code>## Warning: Removed 7 rows containing missing values or values outside the scale range
## (`geom_point()`).</code></pre>
<div class="figure">
<span style="display:block;" id="fig:lag-plots"></span>
<img src="01-intro_files/figure-html/lag-plots-1.png" alt="Gráficos de rezago para lag 1 y lag 7 días. La concentración de puntos en la diagonal sugiere autocorrelación positiva, especialmente en lag 1." width="1152"><p class="caption">
Figure 0.10: Gráficos de rezago para lag 1 y lag 7 días. La concentración de puntos en la diagonal sugiere autocorrelación positiva, especialmente en lag 1.
</p>
</div>
<p><strong>Interpretación de rezagos:</strong></p>
<ul>
<li><p><strong>Lag 1 (día anterior):</strong> La mayoría de los puntos se concentran cerca de la diagonal, indicando autocorrelación positiva débil. Los precios tienden a persistir de un día al siguiente, especialmente en niveles bajos y altos.</p></li>
<li><p><strong>Lag 7 (semana anterior):</strong> Mayor dispersión que lag 1, sugiriendo autocorrelación semanal muy débil. Las ventas de un día específico no predicen confiablemente el mismo día de la semana siguiente, excepto en valores extremos.</p></li>
<li><p><strong>Observación sectorial:</strong> Tesla y Moderna muestran mayor dispersión debido a su alta volatilidad, mientras que activos más estables como J&amp;J presentan patrones más concentrados.</p></li>
</ul>
</div>
<div id="estacionalidad-anual" class="section level2" number="0.9">
<h2>
<span class="header-section-number">0.9</span> Estacionalidad Anual<a class="anchor" aria-label="anchor" href="#estacionalidad-anual"><i class="fas fa-link"></i></a>
</h2>
<p>El análisis de estacionalidad revela patrones recurrentes a lo largo del año calendario, particularmente relevantes durante el período COVID-19.</p>
<div class="figure">
<span style="display:block;" id="fig:estacionalidad"></span>
<img src="01-intro_files/figure-html/estacionalidad-1.png" alt="Patrón de precios mensuales por año. Se identifica claramente el impacto COVID en marzo 2020 y la recuperación diferenciada por sector." width="672"><p class="caption">
Figure 0.11: Patrón de precios mensuales por año. Se identifica claramente el impacto COVID en marzo 2020 y la recuperación diferenciada por sector.
</p>
</div>
<p><strong>Patrones estacionales identificados:</strong></p>
<ul>
<li><p><strong>Marzo 2020:</strong> Caída drástica en todos los activos coincidiendo con el crash COVID-19.</p></li>
<li><p><strong>Noviembre-Diciembre:</strong> Tradicionalmente meses fuertes para mercados financieros, patrón que se mantiene excepto durante 2020.</p></li>
<li><p><strong>Primer trimestre:</strong> Generalmente muestra precios más bajos, con recuperación hacia mediados de año. Patrón interrumpido en 2020 por el COVID.</p></li>
<li><p><strong>Diferencias sectoriales:</strong> El sector tecnológico muestra recuperación más rápida post-marzo 2020, mientras farmacéuticas tienen pico en el período de vacunas (Q4 2020 - Q1 2021).</p></li>
</ul>
</div>
<div id="síntesis-de-visualización" class="section level2" number="0.10">
<h2>
<span class="header-section-number">0.10</span> Síntesis de Visualización<a class="anchor" aria-label="anchor" href="#s%C3%ADntesis-de-visualizaci%C3%B3n"><i class="fas fa-link"></i></a>
</h2>
<p>Las visualizaciones revelan hallazgos clave que serán profundizados en capítulos posteriores:</p>
<ol style="list-style-type: decimal">
<li><p><strong>Impacto COVID-19:</strong> Claro quiebre estructural en marzo 2020 visible en todas las series.</p></li>
<li><p><strong>Divergencia sectorial:</strong> Tecnología muestra recuperación en “V”, mientras farmacéuticas tienen comportamiento más heterogéneo.</p></li>
<li><p><strong>Volatilidad variable:</strong> Moderna (72%) vs J&amp;J (18%) ejemplifican el rango de comportamientos dentro del mismo sector.</p></li>
<li><p><strong>Autocorrelación limitada:</strong> Los rezagos sugieren dependencia débil, indicando que modelos simples de persistencia no serán suficientes.</p></li>
<li><p><strong>Estacionalidad interrumpida:</strong> El COVID-19 alteró patrones estacionales tradicionales, creando un nuevo régimen de mercado.</p></li>
</ol>
<p>Estos patrones motivan el análisis formal de series de tiempo en los capítulos siguientes.</p>

</div>
</div>
  <div class="chapter-nav">
<div class="empty"></div>
<div class="next"><a href="literature.html"><span class="header-section-number">1</span> Literature</a></div>
</div></main><div class="col-md-3 col-lg-2 d-none d-md-block sidebar sidebar-chapter">
    <nav id="toc" data-toggle="toc" aria-label="On this page"><h2>On this page</h2>
      <ul class="nav navbar-nav">
<li><a class="nav-link" href="#propuesta-de-an%C3%A1lisis">Propuesta de Análisis</a></li>
<li>
<a class="nav-link" href="#informaci%C3%B3n-a-utilizar"><span class="header-section-number">0.1</span> Información a Utilizar</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#estad%C3%ADsticas-descriptivas-del-dataset"><span class="header-section-number">0.1.1</span> Estadísticas Descriptivas del Dataset</a></li>
<li><a class="nav-link" href="#comparaci%C3%B3n-por-sector"><span class="header-section-number">0.1.2</span> Comparación por Sector</a></li>
</ul>
</li>
<li>
<a class="nav-link" href="#importancia-del-pron%C3%B3stico-y-valor-agregado"><span class="header-section-number">0.2</span> Importancia del Pronóstico y Valor Agregado</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#el-problema"><span class="header-section-number">0.2.1</span> El Problema</a></li>
<li><a class="nav-link" href="#el-valor-agregado"><span class="header-section-number">0.2.2</span> El Valor Agregado</a></li>
</ul>
</li>
<li><a class="nav-link" href="#fuentes-de-datos-y-permisos-de-uso"><span class="header-section-number">0.3</span> Fuentes de Datos y Permisos de Uso</a></li>
<li><a class="nav-link" href="#impacto-esperado"><span class="header-section-number">0.4</span> Impacto Esperado</a></li>
<li><a class="nav-link" href="#intro"><span class="header-section-number">0.5</span> Visualización de las Series de Tiempo</a></li>
<li>
<a class="nav-link" href="#series-de-tiempo-completas"><span class="header-section-number">0.6</span> Series de Tiempo Completas</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#sector-tecnol%C3%B3gico"><span class="header-section-number">0.6.1</span> Sector Tecnológico</a></li>
<li><a class="nav-link" href="#sector-farmac%C3%A9utico"><span class="header-section-number">0.6.2</span> Sector Farmacéutico</a></li>
</ul>
</li>
<li>
<a class="nav-link" href="#an%C3%A1lisis-con-promedios-m%C3%B3viles"><span class="header-section-number">0.7</span> Análisis con Promedios Móviles</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#promedios-m%C3%B3viles---tecnolog%C3%ADa"><span class="header-section-number">0.7.1</span> Promedios Móviles - Tecnología</a></li>
<li><a class="nav-link" href="#promedios-m%C3%B3viles---farmac%C3%A9uticas"><span class="header-section-number">0.7.2</span> Promedios Móviles - Farmacéuticas</a></li>
</ul>
</li>
<li><a class="nav-link" href="#an%C3%A1lisis-de-rezagos"><span class="header-section-number">0.8</span> Análisis de Rezagos</a></li>
<li><a class="nav-link" href="#estacionalidad-anual"><span class="header-section-number">0.9</span> Estacionalidad Anual</a></li>
<li><a class="nav-link" href="#s%C3%ADntesis-de-visualizaci%C3%B3n"><span class="header-section-number">0.10</span> Síntesis de Visualización</a></li>
</ul>

      <div class="book-extra">
        <ul class="list-unstyled">
          
        </ul>
</div>
    </nav>
</div>

</div>
</div> <!-- .container -->

<footer class="bg-primary text-light mt-5"><div class="container"><div class="row">

  <div class="col-12 col-md-6 mt-3">
    <p>"<strong>Análisis de Series de Tiempo de Precios de Acciones</strong>" was written by Julian Rojas y Natalia Tangarife. It was last built on 2025-10-18.</p>
  </div>

  <div class="col-12 col-md-6 mt-3">
    <p>This book was built by the <a class="text-light" href="https://bookdown.org">bookdown</a> R package.</p>
  </div>

</div></div>
</footer><!-- dynamically load mathjax for compatibility with self-contained --><script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script><script type="text/x-mathjax-config">const popovers = document.querySelectorAll('a.footnote-ref[data-toggle="popover"]');
for (let popover of popovers) {
  const div = document.createElement('div');
  div.setAttribute('style', 'position: absolute; top: 0, left:0; width:0, height:0, overflow: hidden; visibility: hidden;');
  div.innerHTML = popover.getAttribute('data-content');

  var has_math = div.querySelector("span.math");
  if (has_math) {
    document.body.appendChild(div);
    MathJax.Hub.Queue(["Typeset", MathJax.Hub, div]);
    MathJax.Hub.Queue(function() {
      popover.setAttribute('data-content', div.innerHTML);
      document.body.removeChild(div);
    })
  }
}
</script>
</body>
</html>
